create table if not exists public.team_submissions (
 id bigint generated by default as identity primary key,
 team_name text not null,
 proposed_score integer not null default 0 check (proposed_score >= 0),
 proof_url text, submitter_name text, submitter_contact text,
 status text not null default 'pending' check (status in ('pending','approved','rejected')),
 admin_score integer, reviewed_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.teams (
 id bigint generated by default as identity primary key,
 team_name text not null unique,
 score integer not null default 0 check (score >= 0),
 logo_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.team_submissions enable row level security;
alter table public.teams enable row level security;
drop policy if exists "Anyone can submit a team" on public.team_submissions;
create policy "Anyone can submit a team" on public.team_submissions for insert to anon,authenticated with check (status='pending');
drop policy if exists "Admins can read submissions" on public.team_submissions;
create policy "Admins can read submissions" on public.team_submissions for select to authenticated using (exists(select 1 from public.admins a where a.user_id=auth.uid()));
drop policy if exists "Admins can update submissions" on public.team_submissions;
create policy "Admins can update submissions" on public.team_submissions for update to authenticated using (exists(select 1 from public.admins a where a.user_id=auth.uid())) with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));
drop policy if exists "Admins can delete submissions" on public.team_submissions;
create policy "Admins can delete submissions" on public.team_submissions for delete to authenticated using (exists(select 1 from public.admins a where a.user_id=auth.uid()));
drop policy if exists "Public can read teams" on public.teams;
create policy "Public can read teams" on public.teams for select to anon,authenticated using (true);
drop policy if exists "Admins can insert teams" on public.teams;
create policy "Admins can insert teams" on public.teams for insert to authenticated with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));
drop policy if exists "Admins can update teams" on public.teams;
create policy "Admins can update teams" on public.teams for update to authenticated using (exists(select 1 from public.admins a where a.user_id=auth.uid())) with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));
drop policy if exists "Admins can delete teams" on public.teams;
create policy "Admins can delete teams" on public.teams for delete to authenticated using (exists(select 1 from public.admins a where a.user_id=auth.uid()));
create index if not exists teams_score_idx on public.teams(score desc,team_name asc);

-- Storage for team logos and evidence files
insert into storage.buckets (id, name, public) values ('team-assets','team-assets',true) on conflict (id) do update set public=true;
drop policy if exists "Anyone can upload team assets" on storage.objects;
create policy "Anyone can upload team assets" on storage.objects for insert to anon,authenticated with check (bucket_id='team-assets');
drop policy if exists "Anyone can view team assets" on storage.objects;
create policy "Anyone can view team assets" on storage.objects for select to anon,authenticated using (bucket_id='team-assets');
drop policy if exists "Admins can delete team assets" on storage.objects;
create policy "Admins can delete team assets" on storage.objects for delete to authenticated using (bucket_id='team-assets' and exists(select 1 from public.admins a where a.user_id=auth.uid()));

alter table public.team_submissions add column if not exists logo_url text;
alter table public.team_submissions add column if not exists proof_image_url text;
alter table public.team_submissions add column if not exists proof_video_url text;
