import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{supabase}from"./supabase";import"./styles.css";
const Header=({go,admin})=><header><button className="brand"onClick={()=>go("/")}>🏆 FFVN <span>RANKINGS</span></button><nav><button onClick={()=>go("/")}>BXH TOP 100</button><button onClick={()=>go(admin?"/":"/admin")}>{admin?"Trang chủ":"Admin"}</button></nav></header>;
function Public({go}){const[t,setT]=useState([]),[f,setF]=useState({team_name:"",proposed_score:"",proof_url:"",submitter_name:"",submitter_contact:""}),[m,setM]=useState(""),[e,setE]=useState("");
async function load(){const{data,error}=await supabase.from("teams").select("*").order("score",{ascending:false}).order("team_name").limit(100);if(error)setE(error.message);else setT(data||[])}useEffect(()=>{load()},[]);
async function submit(x){x.preventDefault();setM("");setE("");const{error}=await supabase.from("team_submissions").insert({...f,proposed_score:Number(f.proposed_score),status:"pending"});if(error)setE(error.message);else{setM("Đã gửi yêu cầu. Admin sẽ kiểm tra và duyệt.");setF({team_name:"",proposed_score:"",proof_url:"",submitter_name:"",submitter_contact:""})}}
return <><Header go={go}/><main><section className="hero"><div><small>VIETNAM SEMI-PRO FREE FIRE</small><h1>FFVN <b>RANKINGS</b></h1><p>Bảng xếp hạng Top 100 team Free Fire bán chuyên Việt Nam.</p><button onClick={()=>document.getElementById("rank").scrollIntoView()}>Xem Top 100</button></div><div className="heroCard">🏆<strong>TOP 100</strong></div></section><section id="rank"><div className="head"><h2>Top 100 Teams</h2><button className="ghost"onClick={load}>↻ Làm mới</button></div>{e&&<div className="error">{e}</div>}<div className="table"><div className="row th"><span>Hạng</span><span>Team</span><span>Điểm</span></div>{t.map((x,i)=><div className="row"key={x.id}><span>#{i+1}</span><strong>{x.team_name}</strong><b>{x.score.toLocaleString("vi-VN")}</b></div>)}{!t.length&&<div className="empty">Chưa có team được duyệt.</div>}</div></section><section id="submit"><h2>Gửi team để xét duyệt</h2><form onSubmit={submit}>{[["team_name","Tên team"],["proposed_score","Điểm đề xuất"],["proof_url","Link bằng chứng"],["submitter_name","Người gửi"],["submitter_contact","Liên hệ"]].map(([k,l])=><label key={k}>{l}<input required={k==="team_name"||k==="proposed_score"} type={k==="proposed_score"?"number":"text"} value={f[k]} onChange={z=>setF({...f,[k]:z.target.value})}/></label>)}{m&&<div className="success">{m}</div>}{e&&<div className="error">{e}</div>}<button>Gửi yêu cầu</button></form></section></main></>}
function Admin({go}){const[s,setS]=useState(null),[ok,setOk]=useState(false),[subs,setSubs]=useState([]),[teams,setTeams]=useState([]),[email,setEmail]=useState(""),[pw,setPw]=useState(""),[err,setErr]=useState("");
useEffect(()=>{supabase.auth.getSession().then(({data})=>setS(data.session));const{data}=supabase.auth.onAuthStateChange((_e,x)=>setS(x));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(s)check()},[s]);async function check(){const{data,error}=await supabase.from("admins").select("user_id").eq("user_id",s.user.id).maybeSingle();if(error)setErr(error.message);setOk(!!data);if(data)load()}
async function login(e){e.preventDefault();const{data,error}=await supabase.auth.signInWithPassword({email,password:pw});if(error)setErr(error.message);else setS(data.session)}
async function load(){const a=await supabase.from("team_submissions").select("*").eq("status","pending").order("created_at",{ascending:false}),b=await supabase.from("teams").select("*").order("score",{ascending:false});if(a.error||b.error)setErr(a.error?.message||b.error?.message);setSubs(a.data||[]);setTeams(b.data||[])}
async function approve(x){const n=Number(prompt("Điểm chính thức:",x.admin_score??x.proposed_score));if(!Number.isFinite(n)||n<0)return;let r=await supabase.from("team_submissions").update({status:"approved",admin_score:n,reviewed_at:new Date().toISOString()}).eq("id",x.id);if(r.error)return setErr(r.error.message);r=await supabase.from("teams").upsert({team_name:x.team_name,score:n,updated_at:new Date().toISOString()},{onConflict:"team_name"});if(r.error)return setErr(r.error.message);load()}
async function reject(x){if(confirm("Từ chối yêu cầu này?")){await supabase.from("team_submissions").update({status:"rejected",reviewed_at:new Date().toISOString()}).eq("id",x.id);load()}}
async function edit(x){const n=Number(prompt("Điểm mới:",x.score));if(Number.isFinite(n)&&n>=0)await supabase.from("teams").update({score:n,updated_at:new Date().toISOString()}).eq("id",x.id);load()}
async function del(x){if(confirm("Xóa team khỏi BXH?")){await supabase.from("teams").delete().eq("id",x.id);load()}}
if(!s)return <><Header go={go} admin/><main className="admin"><form onSubmit={login}><h1>Admin FFVN</h1><label>Email<input type="email"value={email}onChange={e=>setEmail(e.target.value)}required/></label><label>Mật khẩu<input type="password"value={pw}onChange={e=>setPw(e.target.value)}required/></label>{err&&<div className="error">{err}</div>}<button>Đăng nhập</button></form></main></>;
if(!ok)return <><Header go={go} admin/><main className="admin"><div className="error">Tài khoản này chưa có quyền Admin.</div></main></>;
return <><Header go={go} admin/><main className="admin"><div className="adminTop"><h1>Quản trị FFVN</h1><button className="ghost"onClick={()=>supabase.auth.signOut()}>Đăng xuất</button></div>{err&&<div className="error">{err}</div>}<section><h2>Yêu cầu chờ duyệt ({subs.length})</h2>{subs.map(x=><div className="request"key={x.id}><div><b>{x.team_name}</b><p>Đề xuất: {x.proposed_score} điểm</p>{x.proof_url&&<a href={x.proof_url}target="_blank">Mở bằng chứng ↗</a>}</div><div><button onClick={()=>approve(x)}>✓ Duyệt</button><button className="danger"onClick={()=>reject(x)}>Từ chối</button></div></div>)}</section><section><h2>BXH chính thức</h2>{teams.map((x,i)=><div className="request"key={x.id}><div><b>#{i+1} {x.team_name}</b><p>{x.score} điểm</p></div><div><button className="ghost"onClick={()=>edit(x)}>Sửa điểm</button><button className="danger"onClick={()=>del(x)}>Xóa</button></div></div>)}</section></main></>}
function App(){const[route,setRoute]=useState(location.pathname);const go=p=>{history.pushState({},'',p);setRoute(p)};useEffect(()=>{const f=()=>setRoute(location.pathname);addEventListener("popstate",f);return()=>removeEventListener("popstate",f)},[]);return route.startsWith("/admin")?<Admin go={go}/>:<Public go={go}/>}createRoot(document.getElementById("root")).render(<App/>);